// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	roman "github.com/micbar/tdd-challenge/pkg/roman"
	mock "github.com/stretchr/testify/mock"
	grpc "google.golang.org/grpc"
)

// ClockClient is an autogenerated mock type for the ClockClient type
type ClockClient struct {
	mock.Mock
}

// CurrentTime provides a mock function with given fields: ctx, in, opts
func (_m *ClockClient) CurrentTime(ctx context.Context, in *roman.TimeRequest, opts ...grpc.CallOption) (*roman.TimeResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CurrentTime")
	}

	var r0 *roman.TimeResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *roman.TimeRequest, ...grpc.CallOption) (*roman.TimeResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *roman.TimeRequest, ...grpc.CallOption) *roman.TimeResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*roman.TimeResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *roman.TimeRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClockClient creates a new instance of ClockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClockClient {
	mock := &ClockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
