package roman

import (
	"context"

	"google.golang.org/grpc"
)

//go:generate mockery --name ClockClient

// TimeRequest is the request message for the CurrentTime RPC. It carries no
// fields today, mirroring a protobuf message that may grow over time.
type TimeRequest struct{}

// TimeResponse is the response message for the CurrentTime RPC.
type TimeResponse struct {
	// Time is the wall-clock time in the format `hh:mm:ss`.
	Time string
}

// GetTime returns the Time field, or the zero value when the response is nil.
// This mirrors the nil-safe getters generated by protoc-gen-go.
func (m *TimeResponse) GetTime() string {
	if m == nil {
		return ""
	}
	return m.Time
}

// ClockClient mimics a generated gRPC client stub: RPCs take a context and a
// typed request, accept variadic grpc.CallOptions, and return a typed response
// together with an error carrying a gRPC status code (see google.golang.org/grpc/status).
type ClockClient interface {
	// CurrentTime invokes the (hypothetical) CurrentTime RPC and returns the
	// current time as `hh:mm:ss`. On failure it returns a status error whose
	// code can be inspected with status.Code(err).
	CurrentTime(ctx context.Context, in *TimeRequest, opts ...grpc.CallOption) (*TimeResponse, error)
}